### ISSUE TITLE
[Bug]: Failed to load mod file META-INF/jarjar/spectrelib-forge-0.8.1+1.19 .jar

### ISSUE THREAD

**Issue by J053Fabi0** [TheIllusiveC4/Comforts#97] opened 2022-07-31 14:32 UTC
### Minecraft Version

1.19.1

### What happened?

I installed the `comforts-forge-6.0.0+1.19.1.jar`, and when running the server an error pops up. The error goes away when I delete the mod.

```
[16:26:24] [main/ERROR] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Failed to load mod file META-INF/jarjar/spectrelib-forge-0.[10/669]
.jar from comforts-forge-6.0.0+1.19.1.jar                                                                                               
Exception in thread "main" net.minecraftforge.forgespi.locating.ModFileLoadingException: Failed to load mod file comforts-forge-6.0.0+1.
19.1.jar                                                                                                                                
        at MC-BOOTSTRAP/fmlloader@1.19.1-42.0.1/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.loadModFileFrom(Ja
rInJarDependencyLocator.java:90)                                                                                                        
        at MC-BOOTSTRAP/JarJar@0.3.9/net.minecraftforge.jarjar.selection.JarSelector.recursivelyDetectContainedJars(JarSelector.java:144
)                                                                                                                                       
        at MC-BOOTSTRAP/JarJar@0.3.9/net.minecraftforge.jarjar.selection.JarSelector.detect(JarSelector.java:122)                       
        at MC-BOOTSTRAP/JarJar@0.3.9/net.minecraftforge.jarjar.selection.JarSelector.detectAndSelect(JarSelector.java:33)               
        at MC-BOOTSTRAP/fmlloader@1.19.1-42.0.1/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.scanMods(JarInJarDependencyLocator.java:50)
        at MC-BOOTSTRAP/fmlloader@1.19.1-42.0.1/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:127)
        at MC-BOOTSTRAP/fmlloader@1.19.1-42.0.1/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
        at MC-BOOTSTRAP/fmlloader@1.19.1-42.0.1/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(
TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.nio.file.ProviderNotFoundException: Provider "jij" not found
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:359)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
        at MC-BOOTSTRAP/fmlloader@1.19.1-42.0.1/net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator.loadModFileFrom(Ja
rInJarDependencyLocator.java:83)
        ... 25 more
```

### How do you trigger this bug?

1. Download `comforts-forge-6.0.0+1.19.1.jar` in the server's mods directory.
2. Run `./run.sh`.

### Loader

Forge

### Loader Version

42.0.1

### Mod Version

comforts-forge-6.0.0+1.19.1

**Comment by TheIllusiveC4** [comment] 2022-07-31 20:21
Forge issue, duplicate of https://github.com/illusivesoulworks/comforts/issues/96

**Closed as not planned by TheIllusiveC4** 2022-07-31 20:21 UTC
Labels: type: bug, status: duplicate
