### ISSUE TITLE
 Dimension Whitelist/Blacklist Config option for Non-Exploding Sleeping  Bag/Hammock

### ISSUE THREAD

**Issue by jaxmacky** [TheIllusiveC4/Comforts#28] opened 2019-06-06 03:49 UTC
**Please describe the new feature or change.**

Dimension Whitelist/Blacklist Config option for Non-Exploding Sleeping  Bag/Hammock

**Please describe why you want this feature.**

I am currently Dev'ing a Modpack with Advanced Rocketry. The Dev for that mod, has coded in a variation of the vanilla type beds, to not explode on (any) planets. Would be nice to be able to use Comforts without exploding, but having a whitelist/blacklist would make a nice feature option for PackDevs like myself. 
![2019-06-05_22 48 46](https://user-images.githubusercontent.com/8409769/59005707-2e43cf80-87e4-11e9-9031-edddd97a301f.png)

**Comment by TheIllusiveC4** [comment] 2019-06-06 04:08
Duplicate of https://github.com/TheIllusiveC4/Comforts/issues/24
You're also the author of that previous thread, so I'll just say that my response is the same as before. This compatibility is already possible through Forge, the AdvancedRocketry dev just has to implement it.

**Closed by TheIllusiveC4** 2019-06-06 04:08 UTC
Labels: enhancement
