### ISSUE TITLE
[Bug]: Server crashes upon start

### ISSUE THREAD

**Issue by Jayerd** [TheIllusiveC4/Comforts#100] opened 2022-08-15 09:18 UTC
### Minecraft Version

1.19.2

### What happened?

[main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Failed to load mod file META-INF/jarjar/spectrelib-forge-0.8.1+1.19.jar from comforts-forge-6.0.0-beta.5+1.19.jar

### How do you trigger this bug?

1. I install any version of Comforts in the server file
2. I start the server
3. the server crashes
...

### Loader

Forge

### Loader Version

Forge (41.1.0)

### Mod Version

6.0.0+1.19.2 and 6.0.0-beta.5+1.19

**Comment by TheIllusiveC4** [comment] 2022-08-15 18:20
Duplicate of https://github.com/illusivesoulworks/comforts/issues/96

**Closed as not planned by TheIllusiveC4** 2022-08-15 18:20 UTC
Labels: type: bug, status: duplicate
