### ISSUE TITLE
really minor day progression bug when using sleeping bags

### ISSUE THREAD

**Issue by PurpleHel** [TheIllusiveC4/Comforts#21] opened 2018-11-05 01:21 UTC
comforts-1.12.2-1.3.1
forge 14.23.5.2768
minecraft 12.2
lots of other mods but I don't think they're involved.

I happened to notice that when I slept in a sleeping bag, the day didn't progress. I went to sleep at 8pm on day 11, and woke up at 6am on day 11. For my use case, this doesn't matter, but I know there are mods that trigger stuff based on what day it is of the game, so I figured I'd let you know!

Thanks for an awesome mod!

**Comment by TheIllusiveC4** [comment] 2018-11-05 01:48
I am unable to reproduce this, the day progresses correctly when I tested the sleeping bag just now. 

Although you say that you don't think your other mods are involved, I'm inclined to believe that perhaps one of them messes with the sleep cycle. This is also in line with what I predicted when I first saw this issue because my sleeping bag code doesn't really touch the world time in any way. It delegates back to vanilla logic, so it should always progress normally.

I'm closing this issue for now, but I'd be happy to reopen it if you discover that you can reproduce this issue with only Comforts installed.

**Comment by PurpleHel** [comment] 2018-11-05 03:00
Sure, I'll poke at it with the couple mods that do anything with day progression, see if I can figure out which one it is. I thought I remembered that you had some hacky way of advancing the day, but I must have misremembered, my bad.

**Comment by PurpleHel** [comment] 2018-11-05 03:41
Ok, it happens with just BetterHUD and Comforts, but it *doesn't* happen day 1. I didn't try every single night, but I advanced to 10pm day 8 via /time set 160000, put down a sleeping bag (purple, not that I think *that* matters), and slept in the sleeping bag. Woke up at 6am Day 8.
Mods:
  comforts-1.12.2-1.3.1
  hud-1.4-beta-1.12.2

**Comment by TheIllusiveC4** [comment] 2018-11-05 05:50
Okay, so I did some testing.

1) Using `/time set 160000`, the sleeping bag still advances the day as expected.
2) Minecraft days function in intervals of 24000 ticks, so `/time set 160000` should be Day 6, not Day 8. Is BetterHUD calculating the time correctly?
3) You can check the time yourself without BetterHUD by entering the command `/time query day` for the day and `/time query daytime` for the time of day (in ticks).

I'm led to believe that this is an issue with BetterHUD's time calculations, since they do not match Minecraft's internal time calculations when queried.

**Closed by TheIllusiveC4** 2018-11-05 05:50 UTC
Labels: cannot reproduce

**Comment by PurpleHel** [comment] 2018-11-05 10:18
Huh. *weird* BetterHud *seems* to show the time and day right, based on actual playing, but yeah, /time query day shows the day changing when betterhud doesn't, and what day it is doesn't match up. I'll go ask them. Sorry!
