### ISSUE TITLE
Breaking the head of a sleeping bag crashes servers.

### ISSUE THREAD

**Issue by yrsegal** [TheIllusiveC4/Comforts#29] opened 2019-07-12 01:49 UTC
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.12.2-1.4.1.2
* Forge: 14.23.5.2838
#### Steps to Reproduce: Break the head (white block) of a sleeping bag.

Crash Log: not provided, as this is not a server I have access to.

**Comment by TheIllusiveC4** [comment] 2019-07-12 06:15
I can't reproduce this, so I'll need more information. The crash log is pretty critical to have, but if that's not an option then you'll have to offer some more details about the reproduction steps and/or about the modded environment this took place in.

**Comment by TheIllusiveC4** [comment] 2019-09-07 06:43
Closing this as it has been a while without an update. If this is still an issue and there's more information available, then I'll be happy to re-open it.

**Closed by TheIllusiveC4** 2019-09-07 06:43 UTC
Labels: bug, cannot reproduce
