### ISSUE TITLE
Gane crashes with comforts active

### ISSUE THREAD

**Issue by EezaGeeza** [TheIllusiveC4/Comforts#67] opened 2021-08-06 18:42 UTC
#### Versions (1.17.1-5.0.0.0):
* Comforts:
* Forge
#### Steps to Reproduce: Just rabn the game through CurseForge
[crash-2021-08-06_19.21.45-client.txt](https://github.com/TheIllusiveC4/Comforts/files/6947409/crash-2021-08-06_19.21.45-client.txt)

1.
2.
3.
...

Crash/Debug Logs: Please see [how to share logs](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows#how_to_post_your_logs_to_get_help).

**Comment by TheIllusiveC4** [comment] 2021-08-06 20:05
Duplicate of https://github.com/TheIllusiveC4/Comforts/issues/66
Update to Forge 37.0.19 or higher.

**Closed as completed by TheIllusiveC4** 2021-08-06 20:05 UTC
Labels: type: bug
