### ISSUE TITLE
[Bug]: Crashes on server on 1.19

### ISSUE THREAD

**Issue by mimi-min** [TheIllusiveC4/Comforts#98] opened 2022-08-11 05:45 UTC
### Minecraft Version

1.19.2

### What happened?

It works fine on the client, but when adding it to the server, it crashes on startup.

Here is the log from the console (there wasn't anything new in the crash-logs folder): https://pastebin.com/Cr6mEsEj

### How do you trigger this bug?

1. Install Comforts on server
2. Start server

### Loader

Forge

### Loader Version

Forge 41.1.0

### Mod Version

comforts-forge-6.0.0+1.19.2.jar

### Relevant Log Outputs

https://pastebin.com/Cr6mEsEj

**Comment by TheIllusiveC4** [comment] 2022-08-11 21:35
Duplicate of https://github.com/illusivesoulworks/comforts/issues/96

**Closed as not planned by TheIllusiveC4** 2022-08-11 21:35 UTC
Labels: type: bug, status: duplicate
