### ISSUE TITLE
[Bug]: Game crashes followed by an error 

### ISSUE THREAD

**Issue by AyoTedd** [TheIllusiveC4/Comforts#91] opened 2022-07-13 01:03 UTC
### Minecraft Version

1.19.0

### What happened?

Whenever I open the game, I get the following error:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'spectrelib'!
Exit Code: -1

I cannot run the game unless I remove the mod itself. I tried reinstalling the mod, restarting my computer and optimizing my game (before it started crashing I optimized it). And that's when it started to stop working. 

![image](https://user-images.githubusercontent.com/109137390/178625702-7d2c6cd9-b9b7-49c4-b13d-1ccc003300d4.png)

### How do you trigger this bug?

1. Starting the game via the Launcher
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric - 0.14.8 - 19.1

### Mod Version

comforts-fabric-6.0.0-beta.2+1.19

**Comment by TheIllusiveC4** [comment] 2022-07-13 01:11
Can you provide the crash log? Otherwise, I don't know what caused the crash.

**Comment by AyoTedd** [comment] 2022-07-14 02:14
> Can you provide the crash log? Otherwise, I don't know what caused the crash.
[crash-2022-07-10_06.34.06-fml.txt](https://github.com/illusivesoulworks/comforts/files/9107812/crash-2022-07-10_06.34.06-fml.txt)

**Comment by TheIllusiveC4** [comment] 2022-07-14 03:23
Um, that doesn't seem like the right crash log. For one, that's for Forge and your initial bug report was for Fabric. Secondly, that crash report is crashing because of Cooking For Blockheads, not Comforts.

**Comment by AyoTedd** [comment] 2022-07-15 03:35
> Um, that doesn't seem like the right crash log. For one, that's for Forge and your initial bug report was for Fabric. Secondly, that crash report is crashing because of Cooking For Blockheads, not Comforts.

Ohhhh so it was Forge and Cooking For Blockheads messing up my minecraft?

**Comment by TheIllusiveC4** [comment] 2022-07-15 03:37
I don't know. I'm as confused as you are, because you reported this for Fabric but your crash report is for Forge. And the error codes don't really line up between that crash report and your screenshot.

**Comment by AyoTedd** [comment] 2022-07-15 05:13
> I don't know. I'm as confused as you are, because you reported this for Fabric but your crash report is for Forge. And the error codes don't really line up between that crash report and your screenshot.

I'll remove Forge and the mods and see if that'll work

**Comment by AyoTedd** [comment] 2022-07-15 05:39
[crash-2022-07-14_22.38.07-client.txt](https://github.com/illusivesoulworks/comforts/files/9118139/crash-2022-07-14_22.38.07-client.txt)

**Comment by TheIllusiveC4** [comment] 2022-07-15 06:12
Okay, that seems right this time. So it says it has trouble loading the server configuration file for Comforts. Can you share the `comforts-server.toml` file in your `defaultconfigs` folder?

**Comment by AyoTedd** [comment] 2022-07-15 10:29
> Okay, that seems right this time. So it says it has trouble loading the server configuration file for Comforts. Can you share the `comforts-server.toml` file in your `defaultconfigs` folder?

That's another problem that I saw, it wasn't in the configs folder. Someone said it was corrupeted.
![unknown](https://user-images.githubusercontent.com/109137390/179206033-d91f3c1c-42bd-446c-9bce-f6addde078e2.png)

**Comment by TheIllusiveC4** [comment] 2022-07-15 17:59
That looks like the `configs` folder, can you check your `defaultconfigs` folder instead?

**Comment by AyoTedd** [comment] 2022-07-15 22:26
It wont let me send it, it says its unsupported

**Comment by TheIllusiveC4** [comment] 2022-07-16 03:14
The file? You can just put it in a pastebin instead and send the link.

**Comment by AyoTedd** [comment] 2022-07-16 09:47
When I try uploading the toml file to pastebin it just downloads the file.

**Comment by TheIllusiveC4** [comment] 2022-07-16 21:36
You don't upload the file to pastebin, you just copy and paste to create a new pastebin.

**Comment by AyoTedd** [comment] 2022-07-17 01:37
I tried copying and pasting the file on pastebin but it came out blank, or am I doing it wrong? Sorry about this..

> You don't upload the file to pastebin, you just copy and paste to create a new pastebin.

**Comment by TheIllusiveC4** [comment] 2022-07-17 02:11
I'm not sure what you're doing, but it shouldn't come out blank. If you copy and paste something, the contents should, by definition, come out exactly the same as what you initially copied.

If that's not working for some reason, then try just screenshotting the file's contents.

**Comment by AyoTedd** [comment] 2022-07-17 02:34
> I'm not sure what you're doing, but it shouldn't come out blank. If you copy and paste something, the contents should, by definition, come out exactly the same as what you initially copied.
> 
> If that's not working for some reason, then try just screenshotting the file's contents.

![image](https://user-images.githubusercontent.com/109137390/179381484-9bed81c8-94a5-4926-af64-214abc05cb6b.png)

**Comment by TheIllusiveC4** [comment] 2022-07-17 03:24
Um okay, so it's blank. Which explains why copying and pasting doesn't work. Delete the config file entirely and then restart to let it generate a new one.

**Comment by AyoTedd** [comment] 2022-07-17 03:35
Ok, deleting the config file made it work again, but this time when I try going into a world it takes longer than normal to load in. When I click anywhere it stops responding.

**Comment by TheIllusiveC4** [comment] 2022-07-17 04:27
Okay, for that, then I'd need to see the logs from that session. Either `latest.log` or `debug.log` in your `logs` folder. Note that, unless you did this with only Comforts installed, there's a chance it's not a Comforts issue since your configuration file now works correctly.

**Comment by AyoTedd** [comment] 2022-07-17 06:03
[latest.log](https://github.com/illusivesoulworks/comforts/files/9127109/latest.log)

**Comment by TheIllusiveC4** [comment] 2022-07-17 20:30
Nothing in that log points to Comforts being an issue, though there are errors from other mods. Do you experience that issue with _only_ Comforts installed? In other words, what reason do you have to believe that it is Comforts causing your loading issue now that the config has been fixed?

**Comment by AyoTedd** [comment] 2022-07-18 00:00
This is the first I've used minecraft in about several months, I never had mods on it before, so when I found out about the crash issue, I wanted to make completely sure that it was that mod and none else giving it issues. But since you told me that other mods are giving me errors, it raised my concern a bit more. Is there anywhere I should go to have help for these errors? (Since this is a comforts only github. I'm sorry for all this, really :(

**Comment by TheIllusiveC4** [comment] 2022-07-18 01:57
It's fine, really. I can see you're trying your best, so I'll try my best to help you out. Your initial crash issue was solved by fixing the Comforts configuration file. Now, you say you're having issues with load times and freezing when entering a world. What you need to do is figure out which mod is causing that issue. You can accomplish this by removing mods until you figure out which mod's presence is causing the issue to arise. It _could_ still be a Comforts issue, or another mod entirely, you won't know until you test it yourself.

**Comment by AyoTedd** [comment] 2022-07-18 04:00
> It's fine, really. I can see you're trying your best, so I'll try my best to help you out. Your initial crash issue was solved by fixing the Comforts configuration file. Now, you say you're having issues with load times and freezing when entering a world. What you need to do is figure out which mod is causing that issue. You can accomplish this by removing mods until you figure out which mod's presence is causing the issue to arise. It _could_ still be a Comforts issue, or another mod entirely, you won't know until you test it yourself.

Alright, I'll try that. Thank you for taking the time to help me, I very much appreciate it :)

**Comment by TheIllusiveC4** [comment] 2022-07-18 05:35
You're welcome, happy to help. I'm closing this issue for now as the initial problem has been resolved but feel free to open up a new issue if you discover your new problem is also caused by Comforts.

**Closed as completed by TheIllusiveC4** 2022-07-18 05:35 UTC
Labels: type: bug, status: resolved
